name: PR Checks

on:
  pull_request:
    branches:
      - main
      - master

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

    - name: Build Backend
      run: |
        cd apps/backend
        pnpm build
      continue-on-error: true

    - name: Build Frontend
      run: |
        cd apps/web
        pnpm build
      env:
        NEXT_PUBLIC_API_URL: https://api.example.com
        SKIP_BUILD_PRODUCT_REDIRECTS: 1
        NODE_ENV: production

    - name: Run Tests (if any)
      run: |
        # Add test commands here when you have tests
        echo "No tests configured yet"
      continue-on-error: true

    - name: Comment on PR
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const outcome = '${{ job.status }}';
          const emoji = outcome === 'success' ? '✅' : '⚠️';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${emoji} Build ${outcome}! Apps built successfully but NOT deployed. Merge to main to deploy to production.`
          })
      continue-on-error: true